version: "3.9"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
#  nginx:
#    image: nginx:latest
#    container_name: nginx_reverse_proxy
#    restart: always
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 8003:8002
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
  web:
    image: nginx:latest
    container_name: static-front-web
    restart: always
    depends_on:
      - docker-host
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8088:8081
volumes:
  logvolume01: {}


